### ISSUE TITLE
Errata en el folleto: Aventure

### ISSUE THREAD

**Issue by stormwatch** [stormwatch/antiquanova#57]
En pág. 50 donde dice «conservatorio superior *Hochschule*» debe decir «conservatorio superior (*Hochschule*)» sin paréntesis en cursiva o «conservatorio superior *(Hochschule)*» con paréntesis en cursiva, lo que se vea mejor.

En la pág. 51 hay que dejar en cursiva sólo el nombre del CD *Libres en el sonido*. El resto de los nombres propios van en redonda como aparecen en https://github.com/stormwatch/AntiquaNova/blob/2018/bios/Aventure%20Ensemble/bio%202018%20es.org

**Comment by AntiquaNova** [comment]
eze esta errata no la entendi, ya estaba asi, que habria que cambiar?

**Comment by stormwatch** [comment]
En la ultima versión que recibí MP ya corrigió las cursivas de pág 51. (solo faltarían los paréntesis encerrando «*Hochschule*» y poner «Hochschule» en cursiva pero creo que puedo cerrar el issue. Si te arrepentís podés reabrirlo en cualquier momento.
